import { Banner } from "@/components/Banner/Banner";
import { Container } from "@/components/Container/Container";
import { X } from "@/components/svg/X/X";
import Image from "next/image";
import React from "react";

export const About = () => {
  return (
    <Container id="About">
      <div className="md:grid md:flow-dance md:gap-x-[10px] xl:gap-[2px]">
        <h2 className=" xl:w-[538px] md:w-[269px] w-full md:row-start-1 md:row-end-3 md:text-6xl xl:text-[120px] md:leading-[60px] xl:leading-[120px] text-white text-[40px] font-black font-grotesk uppercase leading-10">
          a Story that started with{" "}
          <span className="text-heroBg w-full">
            one simple <span className="block md:inline">ape</span>
          </span>
        </h2>
        <p className="xl:text-2xl xl:leading-[29px] md:mt-[9px] xl:mt-6 md:text-right md:ml-[38px] xl:ml-[83px] mt-4 text-right text-white text-base font-normal font-messina uppercase leading-[19px]">
          <span className="block md:inline-flex">WHO GOT</span> FED UP WITH
          BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND
          DYNAMIC JOURNEY ON THE <span className="md:block"> YACHT</span>
        </p>
        <div className=" xl:w-[417px] md:w-[269px] mb-10 md:mb-9 xl:mb-10 mt-9 flex flex-col items-center gap-4 md:gap-6 xl:gap-9 md:mt-[68px] xl:mt-14">
          <X className=" xl:w-9 xl:h-9mx-auto " />
          <p className=" xl:text-2xl xl:leading-[29px] md:col-start-1 md:col-end-2 text-center text-white text-xs font-normal font-messina uppercase leading-[14px] md:text-base md:leading-[19px]">
            <span className="block xl:inline">EACH ARTWORK IN THE</span>{" "}
            <span className="md:block xl:inline">COLLECTION TELLS A STORY</span>{" "}
            OF
            <span className="block md:inline"> ONE JOURNEY. ARTS ARE</span>{" "}
            RANDOMLY GENERATED BY USERS
          </p>
        </div>
        <Image
          className=" xl:w-[492px] xl:h-[662px] xl:self-end mx-auto mt-10 md:row-start-2 md:row-end-5 md:col-start-2 md:w-[313px] md:h-[422px] md:mt-0 md:left-[-38px] "
          src="/about_mobil.png"
          alt="Monkey in glasses and hat"
          width={492}
          height={662}
        />
      </div>
      <Banner />
    </Container>
  );
};
