import { Baner } from "@/components/Baner/Baner";
import { Conteiner } from "@/components/Conteiner/Conteiner";
import { X } from "@/components/svg/X/X";
import Image from "next/image";
import React from "react";

export const About = () => {
  return (
    <Conteiner id="About">
      <div className="md:grid md:flow-dance md:gap-x-[10px]">
        <h2 className=" md:w-[269px] w-full md:row-start-1 md:row-end-3 md:text-6xl md:leading-[60px] text-white text-[40px] font-black font-grotesk uppercase leading-10">
          a Story that started with{" "}
          <span className="text-rose-500 w-full">
            one simple <span className="block md:inline">ape</span>
          </span>
        </h2>
        <p className=" md:mt-[9px] md:text-right ml-[38px] mt-4 text-right text-white text-base font-normal font-messina uppercase leading-[19px]">
          <span className="block md:inline-flex">WHO GOT</span> FED UP WITH
          BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND
          DYNAMIC JOURNEY ON THE <span className="md:block"> YACHT</span>
        </p>
        <X className="mt-9 mx-auto md:mt-[68px]" />
        <p className=" md:w-[269px] md:col-start-1 md:col-end-2 md:mt-6  mt-4 text-center text-white text-xs font-normal font-messina uppercase leading-[14px] md:text-base md:leading-[19px]">
          <span className="block">EACH ARTWORK IN THE</span>{" "}
          <span className="md:block">COLLECTION TELLS A STORY</span> OF
          <span className="block md:inline"> ONE JOURNEY. ARTS ARE</span>{" "}
          RANDOMLY GENERATED BY USERS
        </p>
        <Image
          className=" mt-10 md:row-start-2 md:row-end-5 md:col-start-2 md:w-[313px] md:h-[422px] md:mt-0 md:left-[-38px] "
          src="/about_mobil.png"
          alt="some ape"
          width={216}
          height={292}
        />
      </div>
      <Baner />
    </Conteiner>
  );
};
