import { Baner } from "@/components/Baner/Baner";
import { Conteiner } from "@/components/Conteiner/Conteiner";
import { X } from "@/components/svg/X/X";
import Image from "next/image";
import React from "react";

export const About = () => {
  return (
    <Conteiner id="About">
      <h2 className="text-white text-[40px] font-black font-grotesk uppercase leading-10">
        a Story that started with{" "}
        <span className="text-rose-500">
          one simple
          <br />
          ape
        </span>
      </h2>
      <p className=" mt-4 text-right text-white text-base font-normal font-messina uppercase leading-[19px]">
        WHO GOT
        <br />
        FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF
        ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
      </p>
      <X className="mt-9 mx-auto" />
      <p className=" mt-4 text-center text-white text-xs font-normal font-['Messina Sans Mono'] uppercase leading-[14px]">
        EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
        RANDOMLY GENERATED BY USERS
      </p>
      <Image
        className=" mt-10 "
        src="/about_mobil.png"
        alt="some ape"
        width={216}
        height={292}
      />
      <Baner />
    </Conteiner>
  );
};
