// import { Inter } from "next/font/google";
import { Header } from "@/components/Header/Header";
import "./globals.css";
import { Footer } from "@/components/Footer/Footer";
import { biroScript, messinaSans, rightGrotesk } from "@/fonts/fonts";

// import localFont from "next/font/local";

// export const biroScript = localFont({
//   src: "../fonts/BiroScript/BiroScriptPlus.ttf",
//   variable: "--font-biro",
// });

// export const messinaSans = localFont({
//   src: "../fonts/MessinaSans/MessinaSansMono-Regular.ttf",
//   variable: "--font-messina",
// });

// export const rightGrotesk = localFont({
//   src: "../fonts/Right Grotesk/RightGrotesk-CompactBlack.otf",
//   variable: "--font-grotesk",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${biroScript.variable} ${messinaSans.variable} ${rightGrotesk.variable} w-full pt-[54px] relative bg-background`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
